#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

for caseName in box1 box2 doublePendulum
do
    ( cd $caseName && ./Allclean )
done

#------------------------------------------------------------------------------
