#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

for caseName in box1 box2 doublePendulum
do
    ( cd $caseName && ./Allrun )
done

#------------------------------------------------------------------------------
