#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication -s box1 mergeMeshes -overwrite . ../box1
runApplication -s box2 mergeMeshes -overwrite . ../box2

runApplication decomposePar -noFunctionObjects

runParallel $(getApplication)

#------------------------------------------------------------------------------
